---
title: "R Homework #2"
author: "Keino Chichester"
date: "January 12, 2017"
output: html_document
---

```{r}
require(nycflights13)
```

```{r}
clothing <- read.csv ("https://raw.github.com/vincentarelbundock/Rdatasets/master/csv/Ecdat/Clothing.csv")
```

```{r}
clothing <- data.frame(clothing)
View(clothing)
```
```{r}
attach(clothing)
```

```{r}
summary(clothing)
```
```{r}
print(mean(Amount))
print(mean(Recency))
```

```{r}
clothing_v2 <- subset(clothing, Dollar12 >= 100, select = c (ID, Amount, Recency, Freq12, Dollar12, Card))
summary(clothing_v2)
```

```{r}
names(clothing_v2)[names(clothing_v2)=="ID"] <- "ID_Men"
names(clothing_v2)[names(clothing_v2)=="Amount"] <- "Amount_Men"
names(clothing_v2)[names(clothing_v2)=="Recency"] <- "Recency_Men"
names(clothing_v2)[names(clothing_v2)=="Freq12"] <- "Frequency_Men"
names(clothing_v2)[names(clothing_v2)=="Dollar12"] <- "Dollar_Men"
names(clothing_v2)[names(clothing_v2)=="Card"] <- "Card_Men"
```
```{r}
names(clothing_v2)
```

```{r}
summary(clothing_v2)

```

```{r}
str(clothing_v2)
```

```{r}
write.csv(clothing_v2, file="clothing_v2.csv")
```

```{r}
clothing_v2 <- read.csv ("C:/Users/keinc/Documents/R - Week 1 Assignement/clothing_v2.csv")
attach(clothing_v2)
```

```{r}
print(mean(Amount_Men))
print(mean(Amount))
print(mean(Recency_Men))
print(mean(Recency))
```

```{r}

```


```{r}
clothing_v2$Card_Men[clothing_v2$Card_Men == 1] <- "YES"
clothing_v2$Card_Men[clothing_v2$Card_Men == 0] <- "NO"
```
```{r}
head(clothing_v2, n=10)
```


